### ISSUE TITLE
stack build fails (linker error) on hlinear with lts-5.17 and higher (works with lts-5.16)

### ISSUE THREAD

**Issue by aghitza** [martinra/hlinear#2]
Everything is fine with stackage lts-5.16, but we get this error at the end with lts-5.17 and 5.18:

```
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/debug-hlinear/debug-hlinear ...
    /opt/ghitza/hlinear-all/hlinear/.stack-work/install/x86_64-linux/lts-5.17/7.10.3/lib/x86_64-linux-ghc-7.10.3/hflint-0.0.1-5w3Xjs5N6UC5sWbFNGNEZl/libHShflint-0.0.1-5w3Xjs5N6UC5sWbFNGNEZl.a(flint_define_wrappers.o): In function `nmod_inv_wrapper':
    (.text+0x12e): undefined reference to `flint_throw' 
    /opt/ghitza/hlinear-all/hlinear/.stack-work/install/x86_64-linux/lts-5.17/7.10.3/lib/x86_64-linux-ghc-7.10.3/hflint-0.0.1-5w3Xjs5N6UC5sWbFNGNEZl/libHShflint-0.0.1-5w3Xjs5N6UC5sWbFNGNEZl.a(flint_define_wrappers.o): In function `nmod_div_wrapper': 
    (.text+0x182): undefined reference to `flint_throw' 
    collect2: error: ld returned 1 exit status
```

**Comment by martinra** [comment]
Hi Alex,

this means source and library diverge. Look at this:

https://github.com/wbhart/flint2/commit/33594af6976a0f78df938c48d33030389398cef1

It defines flint_throw, but is authored Jan 26. So probably you are working with 
the master branch instead of the, say, 2.5 branch. Can you verify?

Martin

**Comment by aghitza** [comment]
OK, so it turns out I had two libflint's on my system: 2.5.2 installed system-wide from the arch repositories (in /usr/lib), and who knows what version built from scratch in another directory (/opt/stuff/lib).  As soon as I removed the latter (leaving only 2.5.2 installed globally), stack build worked with lts-5.16 and lts-5.17 and lts-5.18.

So I guess this was at the root of the issue, and it's gone now.
